### ISSUE TITLE
Task: Design and setup Home Page & routing

### ISSUE THREAD

**Issue by altam-sh** [q1an-w/Co-Operation-soen341project2023#25]
This would be a template page like a home page which would include key features common to all pages such as 
-The platform name
-A quick access to the home page
-A navigation tab
-Potentially a footer with contact info and credits 
-anything else needed

**Comment by q1an-w** [comment]
Login would be on this page
I see 2 methods:
unified login page, redirect to admin, employer or user depending on per account basis
or
some sort of button to indicate user/admin/employer login

**Comment by im-samwong** [comment]
Basic requirements met.
