### ISSUE TITLE
User Story: Job seeker profile and can be seen by employers.

### ISSUE THREAD

**Issue by im-samwong** [q1an-w/Co-Operation-soen341project2023#3]
User Story: As a job seeker, I want to be able to create a professional profile that showcases my skills, education, and work experience, so that potential employers can see an overview of my qualifications and get in touch with me.

**Comment by q1an-w** [comment]
Non-extensive Task List (to be made into actual issues in future sprints):

- Profile editing component
- Profile preview component
- upload documents (feature)
- Job specific application (feature)

**Comment by JBeauche** [comment]
Acceptance Criteria:
- Profile must include personal information (full name, email, phone number, education, job experience, miscellaneous)

**Comment by JBeauche** [comment]
User story: as a job seeker, I must enter a strong password when creating my account.

Acceptance Criteria:
- Login credentials must be email and a strong password - must have at least 8 characters, contain at least 1 digit, 1 uppercase letter, 1 lowercase letter, and 1 symbol.

**Comment by q1an-w** [comment]
2 story points because: 
- component to view and edit profile (2 points)

**Comment by im-samwong** [comment]
User Story was updated into #71 and #73.
