### ISSUE TITLE
User Story: Admin can moderate all job postings and profiles.

### ISSUE THREAD

**Issue by im-samwong** [q1an-w/Co-Operation-soen341project2023#5]
User Story: As an admin, I want to be able to modify and access any job postings or profiles that use the application.

**Comment by q1an-w** [comment]
4 story points because:
- get user profiles and employer job postings (2 points)
- update information abt users (edit job postings, remove/ add users, edit profiles) (2 points)

**Comment by im-samwong** [comment]
This has been replaced with user stories: #74 #77 #78 #75
