### ISSUE TITLE
User Story: Job seeker view all job postings.

### ISSUE THREAD

**Issue by im-samwong** [q1an-w/Co-Operation-soen341project2023#6]
User Story: As a job seeker, I want to be able to view all available job postings in one same location as well as be able to perform refined searches on it.

**Comment by q1an-w** [comment]
Non-extensive Task List (to be made into actual issues in future sprints):
- Candidate page shows job list
- Job from Job List can be Selected
- Filter Feature
- Search Feature

**Comment by q1an-w** [comment]
4 story points because:
- api needed for list of jobs (2 points)
- clickable job component (for application) (1 point)
- editable user profile (1 point)
