### ISSUE TITLE
User Story: User sign up to application.

### ISSUE THREAD

**Issue by im-samwong** [q1an-w/Co-Operation-soen341project2023#66]
As a user, I want to be able to signup to the web application by creating my own credentials.

3 Story points: 1 point for api setup, 1 learning, and 1 for cookies.

**Comment by PFratt** [comment]
|||
| ------------- | ------------- |
| Tested Requirement | Signing up for an account |
| Quick Description  | Once on the login page:<p>The user should select their user type then input their desired username, email, and password|
| Prerequisite  | Database connected, no user with the given email in the database|
| Input | Username, email, password|
| Expected Output | User account created in the database and the user is redirected to the page corresponding to their chosen user type|
| Observed Output | User account created in the database and the user is redirected to the page corresponding to their chosen user type|
| Verdict| Passed|
| Comments | ---|
