### ISSUE TITLE
User Story: Job seeker has profile.

### ISSUE THREAD

**Issue by im-samwong** [q1an-w/Co-Operation-soen341project2023#71]
As a job seeker, I want to be able to have a profile with some of my basic information and my qualifications.

2 Story points: 1 for basic outline design and 1 for implementation.

**Comment by PFratt** [comment]
|||
| ------------- | ------------- |
| Tested Requirement | Viewing your profile as a candidate|
| Quick Description  | Once on the candidate page:<p>The candidate should be able to click on "View Profile" to see their profile information|
| Prerequisite  | Database connected, candidate logged in, candidate has created a profile|
| Input | Click on "View Profile"|
| Expected Output | The candidate's profile information is displayed|
| Observed Output | The candidate's profile information is displayed|
| Verdict| Passed|
| Comments | ---|
